### ISSUE TITLE
Fork To Auto-Commit For Me

### ISSUE THREAD

**Issue by Faiznurullah** [zuramai/reforestation#1]
Izin Bertanya Kak Saugi, Biar Auto Commit Ini Run Di Github Ku Itu Hanya Tinggal Fork Lalu Ganti Branches, Email Dan Username Sesuai Punya Kita Saja Kan Ya ? Maaf Kak Bertanya Lewat Issues

**Comment by zuramai** [comment]
iya betul

**Comment by Faiznurullah** [comment]
Oke a thank you 😀
